port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
unified-delay: true
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
  - 223.5.5.5
  - 114.114.114.114
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
proxies:
- name: Node-1-198.41.212.130
  type: vless
  server: 198.41.212.130
  port: 443
  uuid: c32e9f81-5d41-4b19-9c17-48f657a82b92
  network: ws
  tls: true
  udp: true
  sni: cf-vless-proxy.jiaoweixie94.workers.dev
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: cf-vless-proxy.jiaoweixie94.workers.dev
- name: Node-2-190.93.244.201
  type: vless
  server: 190.93.244.201
  port: 443
  uuid: c32e9f81-5d41-4b19-9c17-48f657a82b92
  network: ws
  tls: true
  udp: true
  sni: cf-vless-proxy.jiaoweixie94.workers.dev
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: cf-vless-proxy.jiaoweixie94.workers.dev
- name: Node-3-104.16.232.223
  type: vless
  server: 104.16.232.223
  port: 443
  uuid: c32e9f81-5d41-4b19-9c17-48f657a82b92
  network: ws
  tls: true
  udp: true
  sni: cf-vless-proxy.jiaoweixie94.workers.dev
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: cf-vless-proxy.jiaoweixie94.workers.dev
- name: Node-4-188.114.96.125
  type: vless
  server: 188.114.96.125
  port: 443
  uuid: c32e9f81-5d41-4b19-9c17-48f657a82b92
  network: ws
  tls: true
  udp: true
  sni: cf-vless-proxy.jiaoweixie94.workers.dev
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: cf-vless-proxy.jiaoweixie94.workers.dev
- name: Node-5-104.16.241.229
  type: vless
  server: 104.16.241.229
  port: 443
  uuid: c32e9f81-5d41-4b19-9c17-48f657a82b92
  network: ws
  tls: true
  udp: true
  sni: cf-vless-proxy.jiaoweixie94.workers.dev
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: cf-vless-proxy.jiaoweixie94.workers.dev
- name: Node-6-104.27.21.118
  type: vless
  server: 104.27.21.118
  port: 443
  uuid: c32e9f81-5d41-4b19-9c17-48f657a82b92
  network: ws
  tls: true
  udp: true
  sni: cf-vless-proxy.jiaoweixie94.workers.dev
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: cf-vless-proxy.jiaoweixie94.workers.dev
- name: Node-7-190.93.246.67
  type: vless
  server: 190.93.246.67
  port: 443
  uuid: c32e9f81-5d41-4b19-9c17-48f657a82b92
  network: ws
  tls: true
  udp: true
  sni: cf-vless-proxy.jiaoweixie94.workers.dev
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: cf-vless-proxy.jiaoweixie94.workers.dev
- name: Node-8-104.17.127.110
  type: vless
  server: 104.17.127.110
  port: 443
  uuid: c32e9f81-5d41-4b19-9c17-48f657a82b92
  network: ws
  tls: true
  udp: true
  sni: cf-vless-proxy.jiaoweixie94.workers.dev
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: cf-vless-proxy.jiaoweixie94.workers.dev
- name: Node-9-198.41.214.141
  type: vless
  server: 198.41.214.141
  port: 443
  uuid: c32e9f81-5d41-4b19-9c17-48f657a82b92
  network: ws
  tls: true
  udp: true
  sni: cf-vless-proxy.jiaoweixie94.workers.dev
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: cf-vless-proxy.jiaoweixie94.workers.dev
- name: Node-10-188.114.97.144
  type: vless
  server: 188.114.97.144
  port: 443
  uuid: c32e9f81-5d41-4b19-9c17-48f657a82b92
  network: ws
  tls: true
  udp: true
  sni: cf-vless-proxy.jiaoweixie94.workers.dev
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: cf-vless-proxy.jiaoweixie94.workers.dev
- name: Node-11-104.25.105.1
  type: vless
  server: 104.25.105.1
  port: 443
  uuid: c32e9f81-5d41-4b19-9c17-48f657a82b92
  network: ws
  tls: true
  udp: true
  sni: cf-vless-proxy.jiaoweixie94.workers.dev
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: cf-vless-proxy.jiaoweixie94.workers.dev
- name: Node-12-190.93.247.169
  type: vless
  server: 190.93.247.169
  port: 443
  uuid: c32e9f81-5d41-4b19-9c17-48f657a82b92
  network: ws
  tls: true
  udp: true
  sni: cf-vless-proxy.jiaoweixie94.workers.dev
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: cf-vless-proxy.jiaoweixie94.workers.dev
- name: Node-13-104.20.255.53
  type: vless
  server: 104.20.255.53
  port: 443
  uuid: c32e9f81-5d41-4b19-9c17-48f657a82b92
  network: ws
  tls: true
  udp: true
  sni: cf-vless-proxy.jiaoweixie94.workers.dev
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: cf-vless-proxy.jiaoweixie94.workers.dev
- name: Node-14-104.18.228.35
  type: vless
  server: 104.18.228.35
  port: 443
  uuid: c32e9f81-5d41-4b19-9c17-48f657a82b92
  network: ws
  tls: true
  udp: true
  sni: cf-vless-proxy.jiaoweixie94.workers.dev
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: cf-vless-proxy.jiaoweixie94.workers.dev
- name: Node-15-104.21.91.19
  type: vless
  server: 104.21.91.19
  port: 443
  uuid: c32e9f81-5d41-4b19-9c17-48f657a82b92
  network: ws
  tls: true
  udp: true
  sni: cf-vless-proxy.jiaoweixie94.workers.dev
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: cf-vless-proxy.jiaoweixie94.workers.dev
proxy-groups:
- name: Auto-Select
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies:
  - Node-1-198.41.212.130
  - Node-2-190.93.244.201
  - Node-3-104.16.232.223
  - Node-4-188.114.96.125
  - Node-5-104.16.241.229
  - Node-6-104.27.21.118
  - Node-7-190.93.246.67
  - Node-8-104.17.127.110
  - Node-9-198.41.214.141
  - Node-10-188.114.97.144
  - Node-11-104.25.105.1
  - Node-12-190.93.247.169
  - Node-13-104.20.255.53
  - Node-14-104.18.228.35
  - Node-15-104.21.91.19
rules:
- GEOIP,LAN,DIRECT
- GEOIP,CN,DIRECT
- MATCH,Auto-Select
