port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
unified-delay: true
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
  - 223.5.5.5
  - 114.114.114.114
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
proxies:
- name: Node-1-备用端口-直连域名
  type: vless
  server: vless.ai-small.xyz
  port: 2053
  uuid: c32e9f81-5d41-4b19-9c17-48f657a82b92
  network: ws
  tls: true
  udp: true
  servername: vless.ai-small.xyz
  sni: vless.ai-small.xyz
  skip-cert-verify: true
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: vless.ai-small.xyz
- name: Node-2-备用端口-IP-1
  type: vless
  server: 104.16.123.96
  port: 2053
  uuid: c32e9f81-5d41-4b19-9c17-48f657a82b92
  network: ws
  tls: true
  udp: true
  servername: vless.ai-small.xyz
  sni: vless.ai-small.xyz
  skip-cert-verify: true
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: vless.ai-small.xyz
- name: Node-3-备用端口-IP-2
  type: vless
  server: 104.19.146.22
  port: 2053
  uuid: c32e9f81-5d41-4b19-9c17-48f657a82b92
  network: ws
  tls: true
  udp: true
  servername: vless.ai-small.xyz
  sni: vless.ai-small.xyz
  skip-cert-verify: true
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: vless.ai-small.xyz
- name: Node-4-备用端口-IP-3
  type: vless
  server: 162.159.192.1
  port: 2053
  uuid: c32e9f81-5d41-4b19-9c17-48f657a82b92
  network: ws
  tls: true
  udp: true
  servername: vless.ai-small.xyz
  sni: vless.ai-small.xyz
  skip-cert-verify: true
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: vless.ai-small.xyz
- name: Node-5-备用端口-域名-Visa
  type: vless
  server: visa.cn
  port: 2053
  uuid: c32e9f81-5d41-4b19-9c17-48f657a82b92
  network: ws
  tls: true
  udp: true
  servername: vless.ai-small.xyz
  sni: vless.ai-small.xyz
  skip-cert-verify: true
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: vless.ai-small.xyz
proxy-groups:
- name: Auto-Select
  type: select
  proxies:
  - Node-1-备用端口-直连域名
  - Node-2-备用端口-IP-1
  - Node-3-备用端口-IP-2
  - Node-4-备用端口-IP-3
  - Node-5-备用端口-域名-Visa
rules:
- GEOIP,LAN,DIRECT
- GEOIP,CN,DIRECT
- MATCH,Auto-Select
